### ISSUE TITLE
join da club

### ISSUE THREAD

**Issue by hd-deman** [park9140/linter-tslint#3]
You can transfer it to the AtomLinter org if you'd like. You'll still be the maintainer.

**Comment by hd-deman** [comment]
The sooner you do it, the less the statistics of downloads you will lose)

**Comment by hd-deman** [comment]
@park9140 ping

**Comment by park9140** [comment]
@hd-deman got really busy at work this week.  I'll have time friday night or saturday to put the proper time into the feature.

**Comment by hd-deman** [comment]
ok. just check the migration steps:
1. apm unpublish
2. move repo to AtomLInter org
3. fix repo url in package.json
4. publish again
